# Generated by Django 4.1.3 on 2023-03-13 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('security_code', models.CharField(max_length=120, null=True, verbose_name='Security Code')),
                ('email', models.EmailField(max_length=254)),
                ('session_token', models.CharField(max_length=500, verbose_name='Device Session Token')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Security Code Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Service',
                'verbose_name_plural': 'Email Services',
                'db_table': 'email_service',
                'ordering': ('-modified_at',),
                'unique_together': {('email', 'session_token')},
            },
        ),
    ]
